### ISSUE TITLE
能把这个仓库的诞生流程做一个图文或者视频教程吗？

### ISSUE THREAD

**Issue by Bian-Sh** [wcai49/cinemachine_doc_Chinese#6]
简单说来，我想自己尝试维护一个 unity 中文翻译文档，比如 addressable 、inputsystem 、netcode go、UI Toolkit 这些
但是我网站相关零基础。
初步看来，按我的理解，实现一下你这个静态文档分这么几步
1. 原站点页面爬取
2. 静态文档框架选取，配置 、翻译、部署
3. GitHub.io 的使用
这些我都没有干过，能出个教程教一下嘛？
我想，借助现在的AI的，这些文档应该可以更加信达雅了吧！

**Comment by wcai49** [comment]
Hi Bian,  不知道你的计划进行到哪一步了？如果有遇到具体的问题我们可以随时讨论；其实相关的教程在youtube上很多质量也很高，我可以帮你一起找一下（如果需要的话）。

另外你可以通过邮件和我联系，我们讨论相关的问题，这个issue和我们项目本身关系不大，我可能会在一周后close issue
